name: CI
on: [push, workflow_dispatch]
jobs:
  deploy:
    name: "Deploy app"
    runs-on: ubuntu-latest
    steps:
      - name: "Configure SSH key"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/app
          chmod 600 ~/.ssh/app
          cat >>~/.ssh/config <<END
          Host $IP_ADDR
            HostName $IP_ADDR
            User $USERNAME
            IdentityFile ~/.ssh/app
            StrictHostKeyChecking no
          END
        env:
            SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
            IP_ADDR: ${{ secrets.IP_ADDR }}
            USERNAME: ${{ secrets.SERVER_USER }}
      - name: "Install tools "
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "sudo apt-get update && sudo apt-get install -y docker.io"
      - name: "Update repository"
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "rm -rf ${{ github.event.repository.name }}; git clone --depth=1  git@github.com:mouradev1/crud-user-nodejs.git"
      - name: "Deploy new version "
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "docker rm -f crud-app && cd ${{ github.event.repository.name }} && sudo docker build -t crud-app . && docker run -d --name crud-app -p 3000:3000 crud-app"